GET http://localhost:5556

###
GET http://localhost:5556/test
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzOWYyOTkwODI4ZTk0YmJlY2ZiNzYiLCJuYW1lIjoidHJ1b25nMyIsInJvbGUiOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNjg0MjUyMzI5LCJleHAiOjE3MTQyNTIzMjl9.acLI4KX-7NqC6cSVoXR3TaDYjJNdHQc7fa4psUBThL0




###
POST http://localhost:5556/users/sign-up
Content-Type: application/json

{
    "name": "devphamtruong1",
    "email": "dev1@gmail.com",
    "password":"1234567",
    "role": "administrator"
}

###
POST http://localhost:5556/users/sign-in
Content-Type: application/json

{
    "email": "dev1@gmail.com",
    "password":"1234567"
}

###
POST http://localhost:5556/blogs/create
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzOWYyOTkwODI4ZTk0YmJlY2ZiNzYiLCJuYW1lIjoidHJ1b25nMyIsInJvbGUiOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNjg0MjU1NTc4LCJleHAiOjE3MTQyNTU1Nzh9.rGTzIdYqlu7kgoc2bH_YXUvBzv2oAyZRrbjwGQ6t-3Q

{
    "title": "Hoc de ra truong 3", 
    "content": "BTL chuy nganh 01"
}


###
GET  http://localhost:5556/blogs/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDYwMzEzMCwiZXhwIjozMDAwMDAwMDAwMTY4NDYwMzAwMH0.vNDh28JAVbFrAGbv5x_72GY9OW7ikn8BUjiaCATiEZU


###
GET  http://localhost:5556/blogs/6463a7277007a53b66ebaa30
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDYwMzEzMCwiZXhwIjozMDAwMDAwMDAwMTY4NDYwMzAwMH0.vNDh28JAVbFrAGbv5x_72GY9OW7ikn8BUjiaCATiEZU



###
PUT http://localhost:5556/blogs/update
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzOWYyOTkwODI4ZTk0YmJlY2ZiNzYiLCJuYW1lIjoidHJ1b25nMyIsInJvbGUiOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNjg0MjU1NTc4LCJleHAiOjE3MTQyNTU1Nzh9.rGTzIdYqlu7kgoc2bH_YXUvBzv2oAyZRrbjwGQ6t-3Q

{
    "title": "Hoc de ra truong 3 update", 
    "content": "BTL chuy nganh 01 update"
}



###
GET  http://localhost:5556/comment/

###
POST  http://localhost:5556/comment/6463a7277007a53b66ebaa30
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDYwMzEzMCwiZXhwIjozMDAwMDAwMDAwMTY4NDYwMzAwMH0.vNDh28JAVbFrAGbv5x_72GY9OW7ikn8BUjiaCATiEZU

{
    "content" : " bai viet so 1 hay qua"
}

###
GET  http://localhost:5556/comment/6463a7277007a53b66ebaa30
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDYwMzEzMCwiZXhwIjozMDAwMDAwMDAwMTY4NDYwMzAwMH0.vNDh28JAVbFrAGbv5x_72GY9OW7ikn8BUjiaCATiEZU





###
PUT  http://localhost:5556/comment/6463a7277007a53b66ebaa30/64690a8eeecbc25a71fd99ab
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDYwMzEzMCwiZXhwIjozMDAwMDAwMDAwMTY4NDYwMzAwMH0.vNDh28JAVbFrAGbv5x_72GY9OW7ikn8BUjiaCATiEZU

{
    "content" :"hay hay hay da update"
}



###
DELETE   http://localhost:5556/comment/6463a7277007a53b66ebaa30/646980e0e16ef0811d19adcf
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDYwMzEzMCwiZXhwIjozMDAwMDAwMDAwMTY4NDYwMzAwMH0.vNDh28JAVbFrAGbv5x_72GY9OW7ikn8BUjiaCATiEZU




###
POST http://localhost:5556/tag/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDkxOTE4OSwiZXhwIjozMDAwMDAwMDAwMTY4NDkyMDAwMH0.s8Piy_p0njB2SJM9k0s5asuLoyLK9xFa7hqWq4Zk6mA

{
    "name" : "test4",
    "bg_color": "rgb(233,233,233",
    "text_color": "rgb(233,233,233"
    
}


###
GET http://localhost:5556/tag/getalltag
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDkxOTE4OSwiZXhwIjozMDAwMDAwMDAwMTY4NDkyMDAwMH0.s8Piy_p0njB2SJM9k0s5asuLoyLK9xFa7hqWq4Zk6mA



###
GET http://localhost:5556/tag/646de05dc92432cb503df86f/getonetag
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDkxOTE4OSwiZXhwIjozMDAwMDAwMDAwMTY4NDkyMDAwMH0.s8Piy_p0njB2SJM9k0s5asuLoyLK9xFa7hqWq4Zk6mA


###
PUT http://localhost:5556/tag/646dd3b6489f546392158e7d/updatetag
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDkxOTE4OSwiZXhwIjozMDAwMDAwMDAwMTY4NDkyMDAwMH0.s8Piy_p0njB2SJM9k0s5asuLoyLK9xFa7hqWq4Zk6mA


{
    "name": "test update",
    "bg_color": "#242424",
    "text_color": "#242424"

}


###
DELETE http://localhost:5556/tag/646dd3ec489f546392158e7f/delete
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzYjVlZDVkYTFmNDY2ZWVhMjMzZmQiLCJuYW1lIjoiZGV2cGhhbXRydW9uZzEiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTY4NDkxOTE4OSwiZXhwIjozMDAwMDAwMDAwMTY4NDkyMDAwMH0.s8Piy_p0njB2SJM9k0s5asuLoyLK9xFa7hqWq4Zk6mA

